# Services, etc
version: "3.4"
services:
    dnsmasq:
        privileged: true
        build:
            context: services/dnsmasq/
        restart: unless-stopped
        expose:
            - "2222"
        volumes:
            - ./config/dnsmasq/:/app/config
        networks:
            - gc-network

    mumble:
        privileged: true
        build:
            context: services/mumble/
        restart: unless-stopped
        ports:
            - "6120:6120/udp"
            - "6120:6120/tcp"
        expose:
            - "6502"
        volumes:
            - certbot-etc:/etc/letsencrypt/:ro
            - mumble-slice:/usr/share/slice/
            - ./config/mumble/mumble-server.ini:/etc/mumble-server.ini
            - ./data/sql:/var/lib/mumble-server
        networks:
            - gc-network

    nextcloud:
        image: efrecon/webdav-client
        devices:
            - "/dev/fuse:/dev/fuse"
        restart: unless-stopped
        cap_add:
            - SYS_ADMIN
        security_opt: 
            - apparmor:unconfined
        environment:
            - WEBDRIVE_USERNAME=${WEBDRIVE_USERNAME}
            - WEBDRIVE_PASSWORD=${WEBDRIVE_PASSWORD}
            - WEBDRIVE_URL=${WEBDRIVE_URL}
            - DAVFS2_ASK_AUTH=0
        volumes:
            - /mnt/webdrive:/mnt/webdrive:rshared

    benny:
        build:
            context: services/benny/
        restart: unless-stopped
        depends_on:
            - "mumble"
            - "nextcloud"
        volumes:
            - ./config/benny/benny.json:/app/benny.json
            - /mnt/webdrive:/mnt/webdrive:rshared
        networks:
            - gc-network

    botamusique:
        build:
            context: services/botamusique/
        depends_on: 
            - "mumble"
        restart: unless-stopped
        volumes:
            - ./config/botamusique/configuration.ini:/botamusique/configuration.ini
        networks:
            - gc-network

    mumble-json:
        build:
            context: services/mumble-json/
        depends_on: 
            - "mumble"
        restart: unless-stopped
        volumes:
            - web-root:/var/www/html
            - mumble-slice:/usr/share/slice/
        networks:
            - gc-network
        environment: 
            - MUMBLE_URL=mumble:6502
        command: bash mumble-json.sh

    web:
        image: nginx:mainline-alpine
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
        environment: 
            - NGINX_HOST=${NGINX_HOST}
            - NGINX_HTTP_PORT=${NGINX_HTTP_PORT}
            - NGINX_HTTPS_PORT=${NGINX_HTTPS_PORT}
        volumes:
            - ./config/nginx/templates/gc.conf.template:/etc/nginx/templates/gc.conf.template:rw,cached
            - web-root:/var/www/html
            - certbot-etc:/etc/letsencrypt
            - certbot-var:/var/lib/letsencrypt
            - dhparam:/etc/ssl/certs
        networks:
            - gc-network

    certbot:
        image: certbot/certbot
        volumes:
            - certbot-etc:/etc/letsencrypt
            - certbot-var:/var/lib/letsencrypt
            - web-root:/var/www/html
        depends_on:
            - web
        command: "certonly --webroot --webroot-path=/var/www/html --email ${CERT_EMAIL} --agree-tos --no-eff-email ${CERT_DOMAIN}"
        networks:
            - gc-network
        
volumes:
    certbot-etc:
    certbot-var:
    mumble-slice:
    webdrive:
    web-root:
        driver: local
        driver_opts:
            type: none
            device: ${HTML_DIR}
            o: bind
    dhparam:
        driver: local
        driver_opts:
            type: none
            device: ${SSL}
            o: bind

networks:
    gc-network:
        driver: bridge
