# Services, etc
version: "3.4"
services:
    dnsmasq:
        privileged: true
        build:
            context: services/dnsmasq/
        ports:
            - "2222:2222"
        volumes:
            - ./config/dnsmasq/:/app/config

    mumble:
        privileged: true
        build:
            context: services/mumble/
        ports:
            - "64738:64738"
            - "6502:6502"
        volumes:
            - ./config/mumble:/app/config
            - ./data/sql:/var/lib/mumble-server

    benny:
        build:
            context: services/benny/
        depends_on:
            - "mumble"
        volumes:
            - ./config/benny:/app/config

    mumble-json:
        build:
            context: services/mumble-json
        depends_on: 
            - "mumble"
        restart: on-failure
        network_mode: host
        volumes:
            - ./data/json:/app/json

    nginx:
        build:
            context: services/viewer/
        ports:
            - "80:80"
        volumes:
            - ./config/viewer:/app/config