# Services, etc
version: "3.4"
services:
    web:
        image: nginx:mainline-alpine
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - web-root:/var/www/html
            - ./config/nginx/nginx.init.conf:/etc/nginx/nginx.conf:ro
            - certbot-etc:/etc/letsencrypt
            - certbot-var:/var/lib/letsencrypt
            - dhparam:/etc/ssl/certs
        networks:
            - gc-network

    certbot:
        image: certbot/certbot
        volumes:
            - certbot-var:/var/lib/letsencrypt
            - certbot-etc:/etc/letsencrypt
            - web-root:/var/www/html
        depends_on:
            - web
        command: "certonly --webroot --webroot-path=/var/www/html --email ${CERT_EMAIL} --agree-tos --no-eff-email ${CERT_DOMAIN}"
        networks:
            - gc-network
        
volumes:
    certbot-etc:
    certbot-var:
    web-root:
        driver: local
        driver_opts:
            type: none
            device: ${HTML_DIR}
            o: bind
    dhparam:
        driver: local
        driver_opts:
            type: none
            device: ${SSL}
            o: bind


networks:
    gc-network:
        driver: bridge