# Services, etc
version: "3.4"
services:
    dnsmasq:
        privileged: true
        build:
            context: services/dnsmasq/
        ports:
            - "2222:2222"
        volumes:
            - ./config/dnsmasq/:/app/config
        networks:
            - gc-network

    mumble:
        privileged: true
        build:
            context: services/mumble/
        ports:
            - "64738:64738"
            - "6502:6502"
        volumes:
            - ./config/mumble/mumble-server.ini:/etc/mumble-server.ini
            - mumble-slice:/usr/share/slice/
            - ./data/sql:/var/lib/mumble-server
        networks:
            - gc-network

    benny:
        build:
            context: services/benny/
        depends_on:
            - "mumble"
        volumes:
            - ./config/benny/benny.json:/app/benny.json
        networks:
            - gc-network

    botamusique:
        build:
            context: services/botamusique/
        depends_on: 
            - "mumble"
        volumes:
            - ./config/botamusique/configuration.ini:/botamusique/configuration.ini
        networks:
            - gc-network

    mumble-json:
        build:
            context: services/mumble-json/
        depends_on: 
            - "mumble"
        restart: always
        volumes:
            - web-root:/var/www/html
            - mumble-slice:/usr/share/slice/
        networks:
            - gc-network
        environment: 
            - MUMBLE_URL=mumble:6502
        command: bash mumble-json.sh

    web:
        image: nginx:mainline-alpine
        ports:
            - "80:80"
            - "443:443"
        environment: 
            - NGINX_HOST=${NGINX_HOST}
            - NGINX_HTTP_PORT=${NGINX_HTTP_PORT}
            - NGINX_HTTPS_PORT=${NGINX_HTTPS_PORT}
        volumes:
            - ./config/nginx/templates/gc.conf.template:/etc/nginx/templates/gc.conf.template:rw,cached
            - web-root:/var/www/html
            - certbot-etc:/etc/letsencrypt
            - certbot-var:/var/lib/letsencrypt
            - dhparam:/etc/ssl/certs
        networks:
            - gc-network

    certbot:
        image: certbot/certbot
        volumes:
            - certbot-var:/var/lib/letsencrypt
            - certbot-etc:/etc/letsencrypt
            - web-root:/var/www/html
        depends_on:
            - web
        command: "certonly --webroot --webroot-path=/var/www/html --email ${CERT_EMAIL} --agree-tos --no-eff-email ${CERT_DOMAIN}"
        networks:
            - gc-network
        
volumes:
    certbot-etc:
    certbot-var:
    mumble-slice:
    web-root:
        driver: local
        driver_opts:
            type: none
            device: ${HTML_DIR}
            o: bind
    dhparam:
        driver: local
        driver_opts:
            type: none
            device: ${SSL}
            o: bind

networks:
    gc-network:
        driver: bridge