# Services, etc
version: "3"
services:
    dnsmasq:
        privileged: true
        build:
            context: services/dnsmasq/
        ports:
            - "2222:2222"
        volumes:
            - ./config/dnsmasq/:/app/config

    mumble:
        privileged: true
        build:
            context: services/mumble/
        ports:
            - "64738:64738"
        volumes:
            - ./config/mumble:/app/config
            - ./data:/var/lib/mumble-server

    benny:
        build:
            context: services/benny/
        depends_on:
            - "mumble"
        volumes:
            - ./config/benny:/app/config